name: meu_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets\fonts\RobotoMono-VariableFont_wght.ttf
        - asset: assets\fonts\RobotoMono-Italic-VariableFont_wght.ttf
  assets:
    - assets/images/
    - assets/data.json
